### ISSUE TITLE
Custom titleViews always overridden

### ISSUE THREAD

**Issue by joernschmidt** [hectormatos2011/iOSContextualMenu#2]
In `layoutMenuItemsIfNeeded` the titleView is set to a custom view if the delegate responds to the custom view method. Right after that though, there is an if-condition that overrides the `titleView` in any case, either with the regular case or with an invisible Item (line 719), or am I wrong here.

**Comment by mxcl** [comment]
Confirmed.

**Comment by hectormatos2011** [comment]
Fixed in #3. I wasn't getting any notifications on anything with this repo which is weird. So sorry about that!
