### ISSUE TITLE
Methods get called but no menu when launching app from shortcut

### ISSUE THREAD

**Issue by multinerd** [hectormatos2011/iOSContextualMenu#8]
Hi, im having trouble using this framework when launching from a URL scheme. All the necessary methods get called to setup my array, the delegate methods for returning the label and image all gets called but the menu itself never appears when launching from a URL

**Comment by multinerd** [comment]
Seems to do with the way im setting up my view controllers in app delegate when launching from url. allowing the menu to show on modal controllers fixed it for me.

**Comment by hectormatos2011** [comment]
I don't know why I was never notified of this! I'm so sorry about that. Let me look at the PR

**Comment by hectormatos2011** [comment]
Merged. Thank you for that!
